### PR TITLE
Fix handling utf8

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by TingPing** [comment]
Don't merge yet, one more fixup..

**Comment by TingPing** [comment]
ping @rahatarmanahmed

**Comment by rahatarmanahmed** [comment]
Did you fix the thing you told me to wait for?

**Comment by TingPing** [comment]
Yup, should be good to go.

**Comment by rahatarmanahmed** [comment]
Why did you remove the 64-bit project? Now it only compiles the 32-bit version, and consequently I can't test it on my 64-bit HexChat.

**Pull request merged**
